import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Headercustom from '../components/Headercustom'
import Footermain from '../components/Footermain'

export default function aboutus() {
  return (
    <>
      <Head>
        <title>About Office Caller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Headercustom />

      {/* about-section */}
      <div className="section officecaller-cont-wrapper" id="about-section">
        <div className="container">
            <div className="row">
                <div className="col-md-6 col-sm-12">
                    <div className="officecaller-heading">
                        <h2>About Us</h2>
                    </div>
                    <p>Office Caller is an Indian company founded in 2009 in Pune, India by Mr. Sameer Kutty. The brilliant concept behind Office caller is such that any organization could manage their business calls using one single Application. We offer you an all-in-one toolkit that combines chat, calling, meetings, and collaborations for you to work smarter. Our aim is to provide employees with a modern day calling solution within an easy-to-use platform.</p>
                </div>
                <div className="col-md-6 col-sm-12">
                    <div className="cont-wrapper-imgblock">
                        <div className="cont-wrapper-imgblock-shape">
                          <Image src="/images/lightshape.svg" alt="" width={572} height={464} />
                          </div>
                          <Image src="/images/business_deal.svg" alt="" width={636} height={604} style="width: 90%; box-shadow: none; border: none;" />
                    </div>
                </div>
            </div>
        </div>
        <div id="particle-conatiner">
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
            <div className="particle"></div>
        </div>
      </div>

      <Footermain />
    </>
  )
}
