import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Headercustom from '../components/Headercustom'
import Footermain from '../components/Footermain'

export default function aboutus() {
  return (
    <>
      <Head>
        <title>Contact Office Caller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headercustom />

      <h1>Contact Us</h1>

      <Footermain />
    </>
  )
}
